### ISSUE TITLE
Support dependency mappings

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/packit#106]
## Context
[RFC-0010](https://github.com/paketo-buildpacks/rfcs/blob/main/accepted/0010-dependency-mappings.md) has been accepted and so we should enable `packit` to support this feature for our buildpacks.

## Proposal
We could extend the functionality of the `postal` package to support looking up dependency mappings if there are `dependency-mapping` bindings available from the platform.

**Comment by arjun024** [comment]
Related issue: https://github.com/paketo-buildpacks/packit/issues/107

**Comment by sophiewigmore** [comment]
Context from looking into this:

[Documentation on bindings](https://paketo.io/docs/buildpacks/configuration/#bindings) on paketo.io is very helpful.
Noteably:
Bindings set at build-time located: `/platform/bindings`
Bindings set at runtime located: `$SERVICE_BINDING_ROOT` or `$CNB_BINDINGS`

Libcnb does binding lookup [here](https://github.com/buildpacks/libcnb/blob/72c83eef49489b0df0d2d91432579f5ceba84aa3/platform.go#L151).

It might be helpful to emit logs that let the user know we are using the user-provided service bindings rather than the `buildpack.toml` default.

Did some basic preliminary

**Comment by fg-j** [comment]
Given [this RFC](https://github.com/buildpacks/rfcs/blob/main/text/0055-deprecate-service-bindings.md), it seems that the CNB-specific spec for bindings has been deprecated. @paketo-buildpacks/tooling-maintainers should we implement support for both specs, or just the Kubernetes Binding Spec?

**Comment by sophiewigmore** [comment]
@fg-j I believe we said in a meeting at some point we wanted to follow the Kubernetes Binding Spec. Double check with @ryanmoran
