### ISSUE TITLE
Should the matchers in packit be moved into occam?

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/packit#126]
Is there any reason the `matchers` that are currently in `packit` should be there as opposed to a dedicated testing library like `occam`?

**Comment by ryanmoran** [comment]
I think the reason they live in the `packit` repo is because there are tests that use them in the `packit` repo. I searched the org for code references to `MatchTOML` and I can't find anywhere that isn't `packit` or `libpak`. I get that we want to put the test-like things in a testing library, but this matcher was kind of purpose-built for `packit` since it does pretty much all of the TOML parsing. I'd be okay with moving it, but I'm trying to understand what problem this is looking to solve.

**Comment by ForestEckhardt** [comment]
I don't think that I was trying to solve a specific problem. I was more just trying to clean up the `packit` repo where I could and this seemed like an easy win. If this is just not all that high priority then I can drop it and close this issue.

**Comment by ryanmoran** [comment]
I think its kinda complicated by the fact that `occam` already depends on `packit` for `pexec`, I believe. If we then move `matchers` to `occam`, we kinda create a module dependency cycle. I think we'd just generally want to avoid doing that unless it was really solving some other problem. For now, the `matchers` package is self-contained and used only in the `packit` repo. If that changes, maybe we rehash this issue, but for now, I'm hesitant to move it given everything I've outlined here.

**Comment by ForestEckhardt** [comment]
I am more than happy with that answer. I will close for now.
