### ISSUE TITLE
Service Binding - "dependency-mapping" will not work on Windows - colon not allowed in filename

### ISSUE THREAD

**Issue by trv-smaksym3** [paketo-buildpacks/packit#453]
`sha256:b4cb31162ff6d7926dd09e21551fa745fa3ae1758c25148b48dadcf78ab0c24c` as a filename cannot work on windows as '`:`' is not allowed on windows file system

```
$SERVICE_BINDING_ROOT
└── my-dependency-binding
    ├── type -> "dependency-mapping"
    ├── sha256:b4cb31162ff6d7926dd09e21551fa745fa3ae1758c25148b48dadcf78ab0c24c -> https://example.com/dep-1.tgz
    └── sha256:efa6d87993ff21615e2d8fc0c98e07ff357fc9f3b9bd93c2cf58ba7f2b6fd2e0 -> https://example.com/dep-2.tgz
```
link to [dependency-mapping](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0010-dependency-mappings.md#service-binding-specification-for-kubernetes-example) documentation

**Comment by sophiewigmore** [comment]
@trv-smaksym3 sorry for the delay. If this is still relevant for you - are you able to use the `sha256` option from the RFC to avoid the `:`? 
```
$SERVICE_BINDING_ROOT
└── my-dependency-binding
    ├── type -> "dependency-mapping"
    ├── b4cb31162ff6d7926dd09e21551fa745fa3ae1758c25148b48dadcf78ab0c24c -> https://example.com/dep-1.tgz
    └── efa6d87993ff21615e2d8fc0c98e07ff357fc9f3b9bd93c2cf58ba7f2b6fd2e0 -> https://example.com/dep-2.tgz
```

**Comment by sophiewigmore** [comment]
Hey @trv-smaksym3 thanks to @ChuckQuinnIV we have released a new version of packit that allows users to pass dependency mappings with an `_` underscore instead of colon, like `sha256_b4cb31162ff6d7926dd09e21551fa745fa3ae1758c25148b48dadcf78ab0c24c`. This should hopefully resolve your issue. I'm going to close this out as a result of the fix and inactivity, but feel free to reopen should you run into any issues
